---
title: "Planning ClimateLabs"
classoption: landscape
geometry: margin=1cm
header-includes:
  - \usepackage{pgfgantt}
  - \usepackage{textcomp}
  - \usepackage{lscape}
#bibliography: library.bib
output: 
  pdf_document:
    includes:
      in_header: ../assets/WP.tex
#csl: ieee.csl
link-citations: yes
linkcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

(293850 * (1.15/100))*300

```


\begin{workpackage}{DEVELOPMENT WORK PACKAGE}
  \label{wp:develop} %change and use appropriate description

  %%%%%%%%%%%%%%%%%% TOP TABLE %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  % Data for the top table
  \wpstart{1} %Starting Month
  \wpend{36} %End Month
  \wptype{Activity type} %RTD, DEM, MGT, or OTHER

  % Person Months per participant (required, max 7, * for leader)  
  % syntax: \personmonths{Participant number}{value}    (not wp leader)
  %     or  \personmonths{Participant short name}{value} (not wp leader)
  %         \personmonths*{Participant number}{value}    (wp leader)
  % for example:
  \personmonths*{UoP2}{12}
  \personmonths{UoP3}{6}
  \personmonths{UoC}{3}
  % etc.

  \makewptable % Work package summary table
    
  % Work Package Objectives
  \begin{wpobjectives}
    This work package has the following objectives:
    \begin{enumerate}
    \item To develop ....
    \item To apply this ....
    \item etc.
    \end{enumerate}
  \end{wpobjectives}
  
  % Work Package Description
  \begin{wpdescription}
    % Divide work package into multiple tasks.
    % Use \wptask command
    % syntax: \wptask{leader}{contributors}{start-m}{end-m}{title}{description}   
 
    Description of work carried out in WP, broken down into tasks, and
    with role of partners list. Use the \texttt{\textbackslash wptask} command.

    \wptask{UoC}{UoC}{1}{12}{Test}{
      \label{task:wp2test}
      Here we will test the WP Task code. 
    }
    \wptask{UoC}{UoC}{6}{9}{Integrate}{
      \label{task:wp2integrate}
      In this task UZH will integrate the work done in ~\ref{task:wp2test}.
    }    
    \wptask{UoP2}{All other}{9}{12}{Apply}{
      Here all the WP participants will apply the results to...
    }
    
    \paragraph{Role of partners}
    \begin{description}
    \item[Participant short name] will lead Task~\ref{task:wp2integrate}.
    \item[UoC] will..
    \end{description}
  \end{wpdescription}
  
  % Work Package Deliverable
  \begin{wpdeliverables}
    % Data for the deliverables and milestones  tables
    % syntax: \deliverable[delivery date]{nature}{dissemination
    % level}{description} 
    %
    % nature: R = Report, P = Prototype, D = Demonstrator, O = Other
    % dissemination level: PU = Public, PP = Restricted to other
    % programme participants (including the Commission Services), RE =
    % Restricted to a group specified by the consortium (including the
    % Commission Services), CO = Confidential, only for members of the
    % consortium (including the Commission Services).
    % 
    % \wpdeliverable[date]{R}{PU}{A report on \ldots}

    \wpdeliverable[36]{UoC}{R}{PU}{Report on the definition of the model
      specifications.}\label{dev:wp2specs}
    
    \wpdeliverable[12]{UoP3}{R}{PU}{Report on Feasibility study for the model
      implementation.}\label{dev:wp2implementation}

    \wpdeliverable[24]{UoP2}{R}{PU}{Prototype of model
      implementation.}\label{dev:wp2prototype}

  \end{wpdeliverables}

\end{workpackage}




\begin{ganttchart}[vgrid,
   y unit title=0.4cm,
   y unit chart=0.5cm,
   time slot format=isodate-yearmonth,
   time slot unit=month,
   title/.append style={draw=none, fill=RoyalBlue!50!black},
   title label font=\sffamily\bfseries\color{white},
   title label node/.append style={below=-1.6ex},
   title left shift=.05,
   title right shift=-.05,
   title height=1,
   bar/.append style={draw=none, fill=OliveGreen!75},
   bar height=.6,
   bar label font=\normalsize\color{black!50},
   group right shift=0,
   group top shift=.6,
   group height=.3,
   group peaks height=.2,
   bar incomplete/.append style={fill=Maroon}
]{2024-01}{2029-01}
\gantttitlecalendar{year} \\

\ganttgroup{WP1: }{2024-01}{2026-01} \\
\ganttbar[name=T1A]{Task A}{2024-01}{2024-06} \\
\ganttlinkedbar[]{Task B}{2024-08}{2024-09} \\



\ganttset{link/.style={OliveGreen}}


\end{ganttchart}



\noindent\resizebox{\textwidth}{!}{
\begin{tikzpicture}[x=.5cm, y=1cm]

\begin{ganttchart}[vgrid,
   time slot format = isodate-yearmonth,
   bar/.append style={fill=red!50, rounded corners=3pt},
	newline shortcut=true,
	today={\the\year-\the\month-\the\day}, 
   today offset= .5,
	y unit chart=0.6cm,
	x unit = 0.6cm,
	bar label node/.append style={align=left},
	milestone/.append style={fill=blue, rounded corners=1pt},
	milestone label font=\color{blue},
	time slot unit=month ]{2020-01}{2023-01}
	\gantttitlecalendar{year, month} \\



% \ganttgroup{Phase 1: Indicateurs eco-systémiques}{2021-01}{2021-04} \\

   \ganttbar[name=WP5]{\textbf{WP5:}Management and Coordination}{2020-01}{2023-01}\\
   \ganttbar[name=WP3]{\textbf{WP3:}Quality monitoring and evaluation}{2020-01}{2023-01}\\
   \ganttbar[name=WP4.3]{\textbf{WP4.3:}Outreach}{2020-01}{2023-01}\\

   \ganttbar[name=T2.1]{\textbf{WP4.1:}Dissemination plan definition and implementation}{2020-01}{2020-03}\\
   \ganttbar[name=T2.2]{\textbf{WP4.4:}Design and Content Edition}{2020-01}{2020-03}\\
   \ganttbar[name=T2.3]{\textbf{WP1.1:}Changemaker Leader Teams (CLT) building}{2020-02}{2020-06}\\
   \ganttbar[name=T2.4]{\textbf{WP1.3:}External Advisory Boar Conformation}{2020-02}{2020-04}\\
   \ganttbar[name=T2.4]{\textbf{WP1.2:}Kick-Off Meeting in Manizales, Colombia}{2020-03}{2020-06}\\
   \ganttbar[name=T2.4]{\textbf{WP-2.1:} Social Innovation and Climate Mapping}{2020-07}{2020-12}\\
   \ganttbar[name=T2.5]{\textbf{WP2.2:}Design and Development of Online Incubation Labs Program}{2020-10}{2021-06}\\
   \ganttbar[name=T2.5]{\textbf{WP2.4:}Applied Research Pilot Projects}{2021-01}{2022-07}\\

   \ganttbar[name=T2.5]{\textbf{WP2.3:}Implementation of Climatelabs}{2021-05}{2021-10}\\

   \ganttbar[name=T2.5]{\textbf{WP4.2:}Conference in LOrraine}{2021-10}{2021-10}\\
\ganttbar[name=T2.5]{Latin American Applied Research on CLimate Change Conference, MExico}{2022-11}{2022-11}\\

\end{ganttchart}

\end{tikzpicture}
}


Last Updated :  `r format(Sys.time(), '%d %B, %Y')`
